### PR TITLE
Renames module to Prevent Past or Future Dates

### LINKED ISSUE #2: Module naming
I am starting a discussion about the name of this module.  At the moment, that name is `past_future_date_tags`.  Other proposals are:

* prevent past or future dates
* past and future date tags
* dynamic date limiter
* constrain dates
* date constraint
* dynamic date tags

I welcome other suggestions

### PR DESCRIPTION
**Pull request by mbentz-uf**
Close #2

### CODE REVIEW

**Comment by pbchase** [comment]
Here's checklist from the issue:

- [ ] Rename the repo prevent_past_or_future_dates.
- [ ] Edit the README to use the name Prevent Past or Future Dates instead of the old name. This change needs to be reflected in multiple places.
- [ ] Change the name space to PreventPastOrFutureDates in config.json and ExternalModule.php
- [ ] Change the name to Prevent Past or Future Dates in config.json
- [ ] Change the name to Prevent Past or Future Dates in the JS files.
- [ ] Add the new name in the AUTHORS files

**Comment by mbentz-uf** [comment]
Latest commits completes the checklist.

**Comment by pbchase** [comment]
I can't push to your remote, but you need one more fix. You need t put the .js file back into the js folder

```
commit 603531039e7d0e37faae0ea9311fc37f6b27f098 (HEAD -> module_rename)
Author: Philip Chase <pbc@ufl.edu>
Date:   Fri Apr 9 14:58:31 2021 -0400

    Relocate preventPastOrFutureDates.js

diff --git a/preventPastOrFutureDates.js b/js/preventPastOrFutureDates.js
similarity index 100%
rename from preventPastOrFutureDates.js
rename to js/preventPastOrFutureDates.js
```

**Comment by mbentz-uf** [comment]
Sorry for the oversight, it's been resolved.

**Pull request merged**
